[[includes]]
name = "cargo"
taskfile = "tasks/cargo.toml"

[[tasks]]
name = "true"
command = "ruby -e 'exit(0)'"

[[tasks]]
name = "false"
command = "ruby -e 'exit(1)'"

[[tasks]]
name = "sleep1"
command = "ruby -e 'sleep(1)'"

[[tasks]]
name = "sleep2"
command = "ruby -e 'sleep(2)'"

[[tasks]]
name = "sleepn"
command = "ruby -e 'sleep({{CLI_ARGS}})'"
description = "ruby -e 'sleep(n)'"
